# -*- coding: utf-8 -*-
"""Yelping for a Second Helping.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Zk927AU73yBfZ6kaIplmgjylWsUgvtSo

# Yelping For A Second Helping!

#### Brookie: Sunidhi Ayyagari, Sarah Ding, Sophie Gill, Stephanie Ou Yang

### Data Cleaning and Preprocessing

Download the dataset via kagglehub

Dataset can be found here: https://www.kaggle.com/datasets/omkarsabnis/yelp-reviews-dataset/data
"""

import kagglehub
import os

# Download latest version
path = kagglehub.dataset_download("omkarsabnis/yelp-reviews-dataset")

print("Path to dataset files:", path)
print("Files:", os.listdir(path))

"""Read the dataset from the folder into a DataFrame."""

import pandas as pd

file_path = os.path.join(path, 'yelp.csv')
yelp_dataset = pd.read_csv(file_path)

yelp_dataset.dropna(inplace=True)
yelp_dataset.drop_duplicates(inplace=True)
print(len(yelp_dataset))

import re

# Lowercase reivews
yelp_dataset['cleaned_text'] = yelp_dataset['text'].str.lower()
# Remove non-alphabetical characters and puntuation
yelp_dataset['cleaned_text'] = yelp_dataset['cleaned_text'].apply(lambda x: re.sub(r'[^a-zA-Z\s]', '', x))

import nltk
nltk.download('stopwords')
nltk.download('wordnet')

from nltk.corpus import stopwords

# Remove stopwords
stop_words = set(stopwords.words('english'))
yelp_dataset['cleaned_text'] = yelp_dataset['cleaned_text'].apply(lambda x: ' '.join([word for word in x.split() if word not in stop_words]))

from nltk.stem import WordNetLemmatizer
lemmatizer = WordNetLemmatizer()

# Lemmatize
yelp_dataset['cleaned_text'] = yelp_dataset['cleaned_text'].apply(lambda x: ' '.join([lemmatizer.lemmatize(word) for word in x.split()]))

print('Yelp review before text cleaning and preprocessing:')
print(yelp_dataset['text'][0])

print('\nYelp review after text cleaning and preprocessing:')
print(yelp_dataset['cleaned_text'][0])

"""Map the star ratings to 3-class sentiments with

* 1-2 stars : -1
* 3 stars : 0
* 4-5 stars : 1

This will simplify the number of categories for training and label reviews with clearer sentiment scores with -1 being negative, 0 being neutral, and 1 being positive.
"""

# Map ratings to sentiment
rating_to_sentiment = {1: -1, 2: -1, 3: 0, 4: 1, 5: 1}

yelp_dataset['sentiment'] = yelp_dataset['stars'].map(rating_to_sentiment)

print(yelp_dataset.columns)

yelp_dataset.drop(columns=['business_id', 'date', 'text','review_id', 'stars', 'type', 'user_id', 'cool', 'useful', 'funny'], inplace=True)
print(yelp_dataset.columns)

"""### NER

First step is to tokenize. Using a food specific tokenizer from Hugging Face that can be found here: https://huggingface.co/Dizex/InstaFoodRoBERTa-NER

> InstaFoodRoBERTa-NER is a fine-tuned BERT model that is ready to use for Named Entity Recognition of Food entities on social media like informal text (e.g. Instagram, X, Reddit). It has been trained to recognize a single entity: food (FOOD).
"""

!pip install transformers
!pip install torch

from transformers import AutoTokenizer, AutoModelForTokenClassification
from transformers import pipeline

# Load the Hugging Face model
model_name = "Dizex/InstaFoodRoBERTa-NER"
tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModelForTokenClassification.from_pretrained(model_name)

ner_pipeline = pipeline("ner", model=model, tokenizer=tokenizer, aggregation_strategy="simple")

def extract_dishes(text):
    results = ner_pipeline(text)
    return [ent['word'] for ent in results if ent['entity_group'] == 'FOOD']

yelp_dataset['dishes'] = yelp_dataset['cleaned_text'].apply(extract_dishes)
yelp_dataset.to_csv("yelp_with_dishes.csv", index=False)

print(yelp_dataset['cleaned_text'][0])
print(yelp_dataset['dishes'][0])

"""### Sentiment Analysis"""

!apt update && apt install cuda-11-8
!pip install deeplabcut[tf]

!pip install spacy
!spacy download en_core_web_sm

!pip install setfit datasets

from setfit import AbsaModel

model = AbsaModel.from_pretrained(
    "sentence-transformers/all-MiniLM-L6-v2",
    "sentence-transformers/all-MiniLM-L6-v2",
    spacy_model="en_core_web_sm"
)

from sklearn.model_selection import train_test_split
import pandas as pd

# Load dataset
yelp_dataset = pd.read_csv("yelp_with_dishes.csv")

# Prepare dataset
yelp_dataset.rename(columns={'cleaned_text': 'text', 'dishes': 'span', 'sentiment': 'label'}, inplace=True)

from sklearn.model_selection import train_test_split

train_df, temp_test_df = train_test_split(yelp_dataset, test_size=0.4)
eval_df, test_df = train_test_split(temp_test_df, test_size=0.2)

# Down-sample the majority class in the training set
train_resampled_df = train_df.groupby('label').apply(lambda x: x.sample(train_df['label'].value_counts().min())).reset_index(drop=True)

# Convert the resampled train and eval datasets into `Dataset` format
from datasets import Dataset
train_dataset = Dataset.from_pandas(train_resampled_df)
eval_dataset = Dataset.from_pandas(eval_df)

train_dataset = train_dataset.add_column("ordinal", [0] * len(train_dataset))
eval_dataset = eval_dataset.add_column("ordinal", [0] * len(eval_dataset))

# Set the format for PyTorch
train_dataset.set_format("torch")
eval_dataset.set_format("torch")

import random

# Set random seed for reproducibility
random.seed(42)

# Shuffle dataset and select first 1000 rows
small_train_df = train_dataset.shuffle(seed=42).select(range(500))

# Shuffle and select first 500 rows
small_eval_df = eval_dataset.shuffle(seed=42).select(range(250))

import psutil
print(f"Memory Usage: {psutil.virtual_memory().percent}%")

import gc
gc.collect()

CUDA_LAUNCH_BLOCKING=1

!pip install torch

import torch
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model.to(device)

from setfit import AbsaTrainer, TrainingArguments, AbsaModel
from transformers import EarlyStoppingCallback, AutoTokenizer

# Re-initialize the model and tokenizer here
model = AbsaModel.from_pretrained(
    "sentence-transformers/all-MiniLM-L6-v2",
    "sentence-transformers/all-mpnet-base-v2",
    spacy_model="en_core_web_sm",
)

# Load the Hugging Face tokenizer
model_name = "Dizex/InstaFoodRoBERTa-NER"
tokenizer = AutoTokenizer.from_pretrained(model_name)

args = TrainingArguments(
    output_dir="models",
    num_epochs=2,
    use_amp=True,
    batch_size=16,
    eval_strategy="steps",
    eval_steps=50,
    save_steps=50,
    load_best_model_at_end=True,
)

trainer = AbsaTrainer(
    model,
    args=args,
    train_dataset=train_dataset,
    eval_dataset=eval_dataset,
    callbacks=[EarlyStoppingCallback(early_stopping_patience=5)],
)
trainer.train()

model.save_pretrained('fine_tuned_bert_model')
tokenizer.save_pretrained('fine_tuned_bert_model')

X_test = test_df.drop(columns={'label'})
y_test = test_df['label']
predictions = model.predict(X_test)

import numpy as np
from sklearn.metrics import accuracy_score, f1_score, classification_report

# Predicted labels
y_pred = np.argmax(predictions.predictions, axis=1)

# True labels
y_true = predictions.label_ids

# Accuracy
acc = accuracy_score(y_true, y_pred)
f1 = f1_score(y_true, y_pred, average="weighted")  # or "macro" for class-balanced

print(f"Accuracy: {acc:.4f}")
print(f"F1 Score: {f1:.4f}")
print("\nClassification Report:")
print(classification_report(y_true, y_pred, target_names=["negative", "neutral", "positive"]))

import matplotlib.pyplot as plt
from sklearn.metrics import ConfusionMatrixDisplay

ConfusionMatrixDisplay.from_predictions(
    y_true, y_pred, display_labels=["negative", "neutral", "positive"], cmap="Blues"
)
plt.title("Confusion Matrix")
plt.show()

from sklearn.preprocessing import label_binarize
from sklearn.metrics import roc_curve, auc
import matplotlib.pyplot as plt

# Number of classes
n_classes = 3
class_names = ["negative", "neutral", "positive"]

# Binarize true labels for ROC
y_true_bin = label_binarize(y_true, classes=[0, 1, 2])

# Probabilities from the model
y_score = predictions.predictions

# Compute ROC curve and ROC area for each class
fpr = dict()
tpr = dict()
roc_auc = dict()

for i in range(n_classes):
    fpr[i], tpr[i], _ = roc_curve(y_true_bin[:, i], y_score[:, i])
    roc_auc[i] = auc(fpr[i], tpr[i])

# Plot the ROC curves
plt.figure(figsize=(8, 6))
colors = ['red', 'orange', 'green']
for i in range(n_classes):
    plt.plot(fpr[i], tpr[i], color=colors[i], lw=2,
             label=f'{class_names[i]} (AUC = {roc_auc[i]:.2f})')

plt.plot([0, 1], [0, 1], 'k--', lw=1)
plt.xlabel('False Positive Rate')
plt.ylabel('True Positive Rate')
plt.title('ROC Curve (One-vs-Rest)')
plt.legend(loc="lower right")
plt.grid(True)
plt.tight_layout()
plt.show()

def recommend_best_dish(text, dishes, model):
    from datasets import Dataset
    import numpy as np

    input_data = {
        "text": [text] * len(dishes),
        "span": dishes,
        "ordinal": [0] * len(dishes),
    }

    predict_dataset = Dataset.from_dict(input_data)
    predict_dataset.set_format("torch")

    preds = model.predict(predict_dataset)
    pred_labels = np.argmax(preds.predictions, axis=1)
    sentiment_map = {0: "negative", 1: "neutral", 2: "positive"}
    dish_sentiments = [(dish, sentiment_map[label]) for dish, label in zip(dishes, pred_labels)]

    print("Dish Sentiments:")
    for dish, sentiment in dish_sentiments:
        print(f"- {dish}: {sentiment}")

    positive_dishes = [dish for dish, sentiment in dish_sentiments if sentiment == "positive"]
    if positive_dishes:
        return f"Recommended Dish: {positive_dishes[0]}"
    else:
        return "No strongly positive dish mentioned."

recommend_best_dish(
    "The truffle pasta was amazing but the sushi was disappointing.",
    ["truffle pasta", "sushi"],
    model
)